// ======= БАЗА ВОПРОСОВ =======
// category: 'artist' - исполнитель, 'band' - группа, 'song' - песня

const QUESTIONS_BY_THEME = {
  // ===== ВСЕ ЖАНРЫ (смешанные вопросы из всех категорий) =====
  all: [
    // ПОП
     //фото
    { question: 'Как зовут этого короля поп-музыки?', image: 'img/michaeljackson.jpg', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/whitneyhouston.jpg', answer: 'Whitney Houston', category: 'artist' },
    { question: 'Как зовут этого музыканта?', image: 'img/Prince-W2A-copyright-The-Prince-Estate-photo-credit-Mike-Ruiz.jpg', answer: 'Prince', category: 'artist' },
    { question: 'Кто эта поп-звезда?', image: 'img/taylor-swift.jpg', answer: 'Taylor Swift', category: 'artist' },
    { question: 'Имя артиста:', image: 'img/brunomars.jpg', answer: 'Bruno Mars', category: 'artist' },
    { question: 'Кто эта певица с мощным голосом?', image: 'img/adele.png', answer: 'Adele', category: 'artist' },
    { question: 'Кто из певцов появился в сериале "Игра престолов"?', image: 'img/edsheer.png', answer: 'Ed Sheeran', category: 'artist' },
    { question: 'Певец на фото:', image: 'img/harryst.jpg', answer: 'Harry Styles', category: 'artist' },
    { question: 'Певица сыгравшая в "Американской истории ужасов":', image: 'img/ladygaga.jpg', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/lisa.jpg', answer: 'Lisa', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/rose.jpg', answer: 'Rose', category: 'artist' },

    //текстовые вопросы
    { question: 'Кто исполнил "Billie Jean"?', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Кто спел "I Will Always Love You"?', answer: 'Whitney Houston', category: 'artist' },
    { question: 'Кто спел "My Heart Will Go On"?', answer: 'Celine Dion', category: 'artist' },
    { question: 'Кто исполнил "Purple Rain"?', answer: 'Prince', category: 'artist' },
    { question: 'Кто спел "Rolling in the Deep"?', answer: 'Adele', category: 'artist' },
    { question: 'Кто исполнил "Lose Yourself"?', answer: 'Eminem', category: 'artist' },
    { question: 'Кто спел "Shape of You"?', answer: 'Ed Sheeran', category: 'artist' },
    { question: 'Кто исполнил "Bad Guy"?', answer: 'Billie Eilish', category: 'artist' },
    { question: 'Кто спел "Shallow"?', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Кто спел "Wrecking Ball"?', answer: 'Miley Cyrus', category: 'artist' },
    { question: 'Кто исполнил "Roar"?', answer: 'Katy Perry', category: 'artist' },
    { question: 'Кто спел "Happy"?', answer: 'Pharrell Williams', category: 'artist' },
    { question: 'Кто спел "Love Yourself"?', answer: 'Justin Bieber', category: 'artist' },
    { question: 'Кто исполнил "Havana"?', answer: 'Camila Cabello', category: 'artist' },
    { question: 'Кто спел "Shake It Off"?', answer: 'Taylor Swift', category: 'artist' },
    { question: 'Кто автор "Blinding Lights"?', answer: 'The Weeknd', category: 'artist' },
    { question: 'Кто спел "Abracadabra "?', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Кто исполнил "Beat it"?', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Кто исполнил "Cедая ночь"?', answer: 'Юрий Шатунов', category: 'artist' },
    { question: 'Кто исполнил "Credo"?', answer: 'Zivert', category: 'artist' },
    { question: 'Кто исполнил "Знаешь ли ты"?', answer: 'Макsим', category: 'artist' },
    { question: 'Кто спел "Царица"?', answer: 'Anna Asti', category: 'artist' },
    { question: 'Кто спел "Crazy in Love" с JAY-Z?', answer: 'Beyonce', category: 'artist' },
    { question: 'Какой певец исполнил песню "Grenade"?', answer: 'Bruno Mars', category: 'artist' },
    { question: 'Какой певец исполнил песню "As it was"?', answer: 'Harry Styles', category: 'artist' },
    
    // РОК
    { question: 'Кто был вокалистом Queen?', answer: 'Freddie Mercury', category: 'artist' },
    { question: 'Название песни Queen, ставшей гимном рока:', answer: 'we will rock you', category: 'song' },
    { question: 'Легендарная баллада Guns N\' Roses:', answer: 'November Rain', category: 'song' },
    { question: 'Узнайте легендарную группу:', image: 'img/Queen-Bohemian-Rhapsody.jpg', answer: 'queen', category: 'band' },
    { question: 'Группа Курта Кобейна:', answer: 'nirvana', category: 'band' },
    { question: 'Рок-группа с "Stairway to Heaven":', answer: 'led zeppelin', category: 'band' },
    { question: 'Кто спел "Livin\' on a Prayer"?', answer: 'bon jovi', category: 'band' },
    
    // РЭП И ХИП-ХОП
    { question: 'Кто этот рэп-исполнитель?', image: 'img/eminem.jpg', answer: 'eminem', category: 'artist' },
    { question: 'Кто исполнил "Lose Yourself"?', answer: 'eminem', category: 'artist' },
    { question: 'Кто этот рэпер с дредлоками?', image: 'img/snoopdog.jpg', answer: 'snoop dogg', category: 'artist' },
    { question: 'Кто исполнил "Not Afraid"?', answer: 'eminem', category: 'song' },
    { question: 'Какой трек Кендрика Ламара получил Пулитцеровскую премию?', answer: 'damn', category: 'song' },
    { question: 'Кто спел "Sicko Mode"?', answer: 'travis scott', category: 'artist' },
    { question: 'Кто исполнил "God\'s Plan"?', answer: 'drake', category: 'artist' },
    { question: 'Группа, основанная Dr. Dre:', answer: 'nwa', category: 'band' },
    { question: 'Кто спел "Juicy"?', answer: 'notorious big', category: 'artist' },
    { question: 'Кто исполнил "California Love"?', answer: 'tupac', category: 'artist' },
    { question: 'Какой трек 50 Cent стал его прорывом?', answer: 'in da club', category: 'song' },
    { question: 'Кто спел "Old Town Road"?', answer: 'lil nas x', category: 'artist' },
    { question: 'Кто исполнил "The Next Episode"?', answer: 'dr dre', category: 'artist' },
    { question: 'Группа с альбомом "Straight Outta Compton":', answer: 'nwa', category: 'band' },
    { question: 'Кто спел "Humble"?', answer: 'kendrick lamar', category: 'artist' },
    { question: 'Кто исполнил "Gold Digger"?', answer: 'kanye west', category: 'artist' },
    
    // ЭЛЕКТРОНИКА / ТАНЦЕВАЛЬНАЯ
    { question: 'Кто этот диджей?', image: 'img/davidguetta.jpg', answer: 'david guetta', category: 'artist' },
    { question: 'Кто исполнил "Titanium"?', answer: 'david guetta', category: 'artist' },
    { question: 'Кто спел "Wake Me Up"?', answer: 'avicii', category: 'artist' },
    { question: 'Кто исполнил "Animals"?', answer: 'martin garrix', category: 'artist' },
    { question: 'Какой трек Daft Punk стал мировым хитом?', answer: 'get lucky', category: 'song' },
    { question: 'Группа, подарившая нам "Around the World":', answer: 'daft punk', category: 'band' },
    
    // ДЖАЗ / БЛЮЗ
    { question: 'Кто этот джазовый музыкант?', image: 'img/louisarmstrong.jpg', answer: 'louis armstrong', category: 'artist' },
    { question: 'Кто спел "What a Wonderful World"?', answer: 'louis armstrong', category: 'artist' },
    { question: 'Кто автор "Summertime"?', answer: 'george gershwin', category: 'artist' },
    { question: 'Кто этот гитарист блюза?', image: 'img/bbking.jpg', answer: 'bb king', category: 'artist' },
    { question: 'Кто исполнил "The Thrill Is Gone"?', answer: 'bb king', category: 'song' },
    
    // КЛАССИЧЕСКАЯ
    { question: 'Кто этот композитор?', image: 'img/mozart.jpg', answer: 'mozart', category: 'artist' },
    { question: 'Кто написал "Лунную сонату"?', answer: 'beethoven', category: 'artist' },
    { question: 'Кто автор "Времена года"?', answer: 'vivaldi', category: 'artist' },
    { question: 'Кто написал "Реквием"?', answer: 'mozart', category: 'artist' },
  ],
  
  pop: [
    // ===== ИСПОЛНИТЕЛИ (artist) =====

    //фото
    { question: 'Как зовут этого короля поп-музыки?', image: 'img/michaeljackson.jpg', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/whitneyhouston.jpg', answer: 'Whitney Houston', category: 'artist' },
    { question: 'Как зовут этого музыканта?', image: 'img/Prince-W2A-copyright-The-Prince-Estate-photo-credit-Mike-Ruiz.jpg', answer: 'Prince', category: 'artist' },
    { question: 'Кто эта поп-звезда?', image: 'img/taylor-swift.jpg', answer: 'Taylor Swift', category: 'artist' },
    { question: 'Имя артиста:', image: 'img/brunomars.jpg', answer: 'Bruno Mars', category: 'artist' },
    { question: 'Кто эта певица с мощным голосом?', image: 'img/adele.png', answer: 'Adele', category: 'artist' },
    { question: 'Кто из певцов появился в сериале "Игра престолов"?', image: 'img/edsheer.png', answer: 'Ed Sheeran', category: 'artist' },
    { question: 'Певец на фото:', image: 'img/harryst.jpg', answer: 'Harry Styles', category: 'artist' },
    { question: 'Певица сыгравшая в "Американской истории ужасов":', image: 'img/ladygaga.jpg', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/lisa.jpg', answer: 'Lisa', category: 'artist' },
    { question: 'Певица на фото:', image: 'img/rose.jpg', answer: 'Rose', category: 'artist' },

    //текстовые вопросы
    { question: 'Кто исполнил "Billie Jean"?', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Кто спел "I Will Always Love You"?', answer: 'Whitney Houston', category: 'artist' },
    { question: 'Кто спел "My Heart Will Go On"?', answer: 'Celine Dion', category: 'artist' },
    { question: 'Кто исполнил "Purple Rain"?', answer: 'Prince', category: 'artist' },
    { question: 'Кто спел "Rolling in the Deep"?', answer: 'Adele', category: 'artist' },
    { question: 'Кто исполнил "Lose Yourself"?', answer: 'Eminem', category: 'artist' },
    { question: 'Кто спел "Shape of You"?', answer: 'Ed Sheeran', category: 'artist' },
    { question: 'Кто исполнил "Bad Guy"?', answer: 'Billie Eilish', category: 'artist' },
    { question: 'Кто спел "Shallow"?', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Кто спел "Wrecking Ball"?', answer: 'Miley Cyrus', category: 'artist' },
    { question: 'Кто исполнил "Roar"?', answer: 'Katy Perry', category: 'artist' },
    { question: 'Кто спел "Happy"?', answer: 'Pharrell Williams', category: 'artist' },
    { question: 'Кто спел "Love Yourself"?', answer: 'Justin Bieber', category: 'artist' },
    { question: 'Кто исполнил "Havana"?', answer: 'Camila Cabello', category: 'artist' },
    { question: 'Кто спел "Shake It Off"?', answer: 'Taylor Swift', category: 'artist' },
    { question: 'Кто автор "Blinding Lights"?', answer: 'The Weeknd', category: 'artist' },
    { question: 'Кто спел "Abracadabra "?', answer: 'Lady Gaga', category: 'artist' },
    { question: 'Кто исполнил "Beat it"?', answer: 'Michael Jackson', category: 'artist' },
    { question: 'Кто исполнил "Cедая ночь"?', answer: 'Юрий Шатунов', category: 'artist' },
    { question: 'Кто исполнил "Credo"?', answer: 'Zivert', category: 'artist' },
    { question: 'Кто исполнил "Знаешь ли ты"?', answer: 'Макsим', category: 'artist' },
    { question: 'Кто спел "Царица"?', answer: 'Anna Asti', category: 'artist' },
    { question: 'Кто спел "Crazy in Love" с JAY-Z?', answer: 'Beyonce', category: 'artist' },
    { question: 'Какой певец исполнил песню "Grenade"?', answer: 'Bruno Mars', category: 'artist' },
    { question: 'Какой певец исполнил песню "As it was"?', answer: 'Harry Styles', category: 'artist' },

    
    // ===== ПЕСНИ (song) =====
   // { question: 'Как называется эта песня ABBA?', image: 'https://picsum.photos/seed/abba/400/200', answer: 'waterloo', category: 'song' },
    //{ question: 'Узнайте хит Адель:', image: 'https://picsum.photos/seed/adele2/400/200', answer: 'someone like you', category: 'song' },
    { question: 'Какой хит группы ABBA стал символом 70-х?', answer: 'Waterloo', category: 'song' },
    { question: 'песня о парне, который расстался с Адель', answer: 'Someone like you', category: 'song' },
    { question: 'Песня Майкла Джексона с клипом-короткометражкой:', answer: 'Thriller', category: 'song' },
    { question: 'Песня Уитни Хьюстон из фильма "Телохранитель":', answer: 'i will always love you', category: 'song' },
    { question: 'Песня, прославившая Билли Айлиш:', answer: 'Bad guy', category: 'song' },
    { question: 'Трек, за который Адель получила "Грэмми":', answer: 'Rolling in the deep', category: 'song' },
    { question: 'Песня из фильма "Титаник":', answer: 'My heart will go on', category: 'song' },
    { question: 'Трек Джастина Бибера из альбома "Purpose":', answer: 'love yourself', category: 'song' },
    { question: 'Песня Тейлор Свифт о расставании:', answer: 'we are never ever getting back together', category: 'song' },
    { question: 'Песня Бруно Марса и Леди Гаги:', answer: 'Die with a Smile', category: 'song' },
    { question: 'Какая песня Монеточки попала в фильм о человеке пауке?', answer: 'Монополия', category: 'song' },
    { question: 'Хит группы Tame Impala:', answer: 'Dracula', category: 'song' },
    { question: 'Хит от Майли Сайрус, пропитанный девизом «я все смогу сама»:', answer: 'Flowers', category: 'song' },
    { question: 'Песня Бруно Марса и Розе:»', answer: 'Apt.', category: 'song' },
    
    // ===== ГРУППЫ (band) =====
    { question: 'Узнайте эту группу:', image: 'img/abba.jpeg', answer: 'ABBA', category: 'band' },
    { question: 'Кто спел "Girls Like You"?', answer: 'Maroon 5', category: 'band' },
    { question: 'Шведская группа, подарившая нам "Dancing Queen":', answer: 'ABBA', category: 'band' },
    { question: 'Группа Джастина Тимберлейка:', answer: 'NSYNC', category: 'band' },
    { question: 'Бойз-бенд, спецщий "I Want It That Way":', answer: 'Backstreet Boys', category: 'band' },
    { question: 'Группа с песней "Bye Bye Bye":', answer: 'nsync', category: 'band' },
    { question: 'Поп-группа "Spice Girls":', answer: 'spice girls', category: 'band' },
    { question: 'Австралийская группа "Kylie Minogue"?', answer: 'the seekers', category: 'band' },
  ],
  
  rock: [
    // ===== ИСПОЛНИТЕЛИ (artist) =====
    { question: 'Кто этот легендарный вокалист?', image: 'img/freddie.jpg', answer: 'Freddie Mercury', category: 'artist' },
    { question: 'Узнайте гитариста:', image: 'https://avatars.mds.yandex.net/i?id=e228a5f8bec33b60073bde55b7f3cdab_l-5668624-images-thumbs&n=13', answer: 'Jimi Hendrix', category: 'artist' },
    { question: 'Кто этот рок-музыкант?', image: 'img/kurt.jpg', answer: 'Kurt Cobain', category: 'artist' },
    { question: 'Узнайте фронтмена:', image: 'img/axl.jpg', answer: 'Axl Rose', category: 'artist' },
    { question: 'Кто этот гитарный гений?', image: 'img/jimmypage.jpg', answer: 'Jimmy Page', category: 'artist' },
    { question: 'Кто был вокалистом Queen?', answer: 'Freddie Mercury', category: 'artist' },
    { question: 'Легендарный гитарист Джими:', answer: 'Jimi Hendrix', category: 'artist' },
    { question: 'Кто автор "Imagine"?', answer: 'John Lennon', category: 'artist' },
    { question: 'Кто спел "Born to Run"?', answer: 'Bruce Springsteen', category: 'artist' },
    { question: 'Кто автор "Johnny B. Goode"?', answer: 'Chuck Berry', category: 'artist' },
    { question: 'Вокалист Guns N\' Roses:', answer: 'Axl Rose', category: 'artist' },
    { question: 'Гитарист Led Zeppelin:', answer: 'Jimmy Page', category: 'artist' },
    { question: 'Кто был вокалистом Nirvana?', answer: 'Kurt Cobain', category: 'artist' },
    { question: 'Барабанщик The Beatles:', answer: 'Ringo Starr', category: 'artist' },
    { question: 'Вокалист The Rolling Stones:', answer: 'Mick Jagger', category: 'artist' },
    { question: 'Гитарист Pink Floyd:', answer: 'David Gilmour', category: 'artist' },
    { question: 'Автор "Hotel California":', answer: 'Don Henley', category: 'artist' },
    { question: 'Вокалист AC/DC:', answer: 'Brian Johnson', category: 'artist' },
    
    // ===== ГРУППЫ (band) =====
    { question: 'Узнайте легендарную группу:', image: 'img/Queen-Bohemian-Rhapsody.jpg', answer: 'queen', category: 'band' },
    { question: 'Узнайте группу по фото:', image: 'img/nirvana.jpg', answer: 'nirvana', category: 'band' },
    { question: 'Узнайте рок-группу:', image: 'img/ledzeppelin.jpg', answer: 'led zeppelin', category: 'band' },
    { question: 'Кто эти рок-легенды?', image: 'img/Pink_Floyd.jpg', answer: 'pink floyd', category: 'band' },
    { question: 'Узнайте группу:', image: 'img/the rolling stones.jpg', answer: 'the rolling stones', category: 'band' },
    { question: 'Группа Курта Кобейна:', answer: 'nirvana', category: 'band' },
    { question: 'Рок-группа с "Stairway to Heaven":', answer: 'led zeppelin', category: 'band' },
    { question: 'Группа "Another Brick in the Wall":', answer: 'pink floyd', category: 'band' },
    { question: 'Кто исполнил "Sweet Child O\' Mine"?', answer: 'guns n roses', category: 'band' },
    { question: 'Группа с Миком Джаггером:', answer: 'the rolling stones', category: 'band' },
    { question: 'Британская группа с Полом Маккартни:', answer: 'the beatles', category: 'band' },
    { question: 'Группа "Smoke on the Water":', answer: 'deep purple', category: 'band' },
    { question: 'Кто спел "Livin\' on a Prayer"?', answer: 'bon jovi', category: 'band' },
    { question: 'Группа "My Generation":', answer: 'the who', category: 'band' },
    { question: 'Группа "Master of Puppets":', answer: 'metallica', category: 'band' },
    { question: 'Кто написал "Hotel California"?', answer: 'eagles', category: 'band' },
    { question: 'Группа "Zombie":', answer: 'the cranberries', category: 'band' },
    { question: 'Кто спел "Wonderwall"?', answer: 'oasis', category: 'band' },
    { question: 'Группа "Back in Black":', answer: 'AC/DC', category: 'band' },
    { question: 'Кто исполнил "November Rain"?', answer: 'guns n roses', category: 'band' },
    { question: 'Группа "The Show Must Go On":', answer: 'queen', category: 'band' },
    { question: 'Кто спел "House of the Rising Sun"?', answer: 'the animals', category: 'band' },
    { question: 'Группа "Light My Fire":', answer: 'the doors', category: 'band' },
    { question: 'Кто исполнил "Whole Lotta Love"?', answer: 'led zeppelin', category: 'band' },
    
    // ===== ПЕСНИ (song) =====
    { question: 'Как называется эта песня Queen?', image: 'https://picsum.photos/seed/bohemian/400/200', answer: 'bohemian rhapsody', category: 'song' },
    { question: 'Узнайте хит Nirvana:', image: 'https://picsum.photos/seed/smells/400/200', answer: 'smells like teen spirit', category: 'song' },
    { question: 'Название песни Queen, ставшей гимном рока:', answer: 'we will rock you', category: 'song' },
    { question: 'Какой трек унесся в космос с Вояджером?', answer: 'johnny b goode', category: 'song' },
    { question: 'Легендарная баллада Guns N\' Roses:', answer: 'november rain', category: 'song' },
    { question: 'Какую песню спел Фредди Меркьюри на Live Aid?', answer: 'bohemian rhapsody', category: 'song' },
    { question: 'Самый известный хит The Beatles:', answer: 'hey jude', category: 'song' },
    { question: 'Песня Led Zeppelin из фильма "Назад в будущее":', answer: 'stairway to heaven', category: 'song' },
    { question: 'Хит AC/DC из 1979 года:', answer: 'highway to hell', category: 'song' },
    { question: 'Песня Metallica из альбома "Metallica":', answer: 'enter sandman', category: 'song' },
    { question: 'Гимн рок-музыки от Queen:', answer: 'we are the champions', category: 'song' },
    { question: 'Песня Nirvana из 1991 года:', answer: 'smells like teen spirit', category: 'song' },
    { question: 'Хит Pink Floyd из "The Wall":', answer: 'another brick in the wall', category: 'song' },
    { question: 'Песня The Rolling Stones 1965 года:', answer: 'satisfaction', category: 'song' },
    { question: 'Баллада Eagles из 1976 года:', answer: 'hotel california', category: 'song' },
    { question: 'Песня Deep Purple 1972 года:', answer: 'smoke on the water', category: 'song' },
    { question: 'Хит Bon Jovi из 1986 года:', answer: 'livin on a prayer', category: 'song' },
  ],
  
  // ===== РЭП И ХИП-ХОП =====
  rap: [
    // ===== ИСПОЛНИТЕЛИ (artist) =====
    { question: 'Узнайте рэпера:', image: 'img/eminem.jpg', answer: 'Eminem', category: 'artist' },
    { question: 'Узнайте рэпера по фото:', image: 'img/snoopdog.jpg', answer: 'snoop dogg', category: 'artist' },
    { question: 'Кто этот рэпер с татуировками?', image: 'img/tupac.jpg', answer: 'tupac', category: 'artist' },
    { question: 'Узнайте рэпера в очках:', image: 'img/kanyewest.jpg', answer: 'kanye west', category: 'artist' },
    { question: 'Кто этот канадский рэпер?', image: 'img/drake.jpg', answer: 'drake', category: 'artist' },
    { question: 'Кто исполнил "Lose Yourself"?', answer: 'eminem', category: 'artist' },
    { question: 'Кто спел "Sicko Mode"?', answer: 'travis scott', category: 'artist' },
    { question: 'Кто исполнил "God\'s Plan"?', answer: 'drake', category: 'artist' },
    { question: 'Кто спел "Juicy"?', answer: 'notorious big', category: 'artist' },
    { question: 'Кто исполнил "California Love"?', answer: 'tupac', category: 'artist' },
    { question: 'Кто спел "Old Town Road"?', answer: 'lil nas x', category: 'artist' },
    { question: 'Кто исполнил "The Next Episode"?', answer: 'dr dre', category: 'artist' },
    { question: 'Кто спел "Humble"?', answer: 'kendrick lamar', category: 'artist' },
    { question: 'Кто исполнил "Gold Digger"?', answer: 'kanye west', category: 'artist' },
    { question: 'Кто спел "Rap God"?', answer: 'eminem', category: 'artist' },
    { question: 'Кто исполнил "Sicko Mode"?', answer: 'travis scott', category: 'artist' },
    { question: 'Кто спел "Hotline Bling"?', answer: 'drake', category: 'artist' },
    { question: 'Кто исполнил "Nuthin\' But a "G" Thang"?', answer: 'dr dre', category: 'artist' },
    { question: 'Кто спел "All Falls Down"?', answer: 'kanye west', category: 'artist' },
    { question: 'Кто исполнил "Alright"?', answer: 'kendrick lamar', category: 'artist' },
    
    // ===== ПЕСНИ (song) =====
    { question: 'Как называется этот трек Эминема?', image: 'https://picsum.photos/seed/loseyourself/400/200', answer: 'lose yourself', category: 'song' },
    { question: 'Какой трек Кендрика Ламара получил Пулитцеровскую премию?', answer: 'damn', category: 'song' },
    { question: 'Какой трек 50 Cent стал его прорывом?', answer: 'in da club', category: 'song' },
    { question: 'Какой трек Уитни Хьюстон стал одним из самых продаваемых?', answer: 'i will always love you', category: 'song' },
    { question: 'Какой трек стал визитной карточкой Snoop Dogg?', answer: 'gin and juice', category: 'song' },
    { question: 'Какой трек Dr. Dre с участием Snoop Dogg стал классикой?', answer: 'the next episode', category: 'song' },
    { question: 'Какой трек Дрейка стал мировым хитом в 2016?', answer: 'one dance', category: 'song' },
    { question: 'Какой трек Канье Уэста содержит семпл Daft Punk?', answer: 'stronger', category: 'song' },
    { question: 'Какой трек стал посмертным хитом Тупака?', answer: 'changes', category: 'song' },
    { question: 'Какой трек The Notorious B.I.G. стал классикой восточного побережья?', answer: 'juicy', category: 'song' },
    { question: 'Какой трек Трэвиса Скотта стал вирусным в TikTok?', answer: 'sicko mode', category: 'song' },
    
    // ===== ГРУППЫ (band) =====
    { question: 'Группа, основанная Dr. Dre:', answer: 'nwa', category: 'band' },
    { question: 'Группа с альбомом "Straight Outta Compton":', answer: 'nwa', category: 'band' },
    { question: 'Группа, в которой начинал Eminem:', answer: 'd12', category: 'band' },
    { question: 'Группа, созданная Pharrell Williams:', answer: 'nerd', category: 'band' },
    { question: 'Группа, с которой сотрудничал Канье Уэст:', answer: 'kids see ghosts', category: 'band' },
    { question: 'Группа, в которую входил Tupac:', answer: 'digital underground', category: 'band' },
  ]
};